version: "3.7"
services:
  admin:
    build:
      context: .
      target: "develop-stage"
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
      - "app/node_modules"
    tty: true
    command: npm run dev
